lib/bson/binary.rb
spec/bson/binary_spec.rb

See Mongoid issue mongoid/mongoid#3780.

Allow using Binary as hash keys.

---

lib/bson/regexp.rb
spec/bson/regexp_spec.rb

Ruby's Regexp method allows for a ton of methods that BSON::Regexp::Raw
does not define. This change lets any method not defined by the
BSON::Regexp::Raw class to be delegated to the underlying Regexp object
provided by BSON::Regexp::Raw#compile. It should cut down on boilerplate
code on the app level that allows you to use a BSON::Regexp::Raw as a Regexp,
by calling methods like match(), scan(), etc.

Allow BSON::Regexp to delegate methods to Regexp

---

lib/bson/binary.rb
spec/bson/binary_spec.rb

After your recent changes we are not able to use a binary field with mongoid.
We used ActiveSupport::Gzip to compress a string, then we have a binary encoded to ascii-8bit, which is the default encoding for a binary, but when mongoid call your ".inspect" method, it raises because incompatible encoding type. It was expected to get utf8 encoding but receives ascii8-bit.

Issue when using a binary field with mongoid

---

lib/bson/document.rb

A common practice in rails is to `#slice` hash by array of symbols. `#slice` [expects](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/hash/slice.rb#L22) any conversion on key to happen in `#convert_key` method. That was made to support `HashWithIndifferentAccess`. [Implementation of `#convert_key` in HashWithIndifferentAccess](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/activesupport/lib/active_support/hash_with_indifferent_access.rb#L258)
before this changes:
```ruby
bson_doc = BSON::Document.new(hello: 'world')
bson_doc.slice(:hello) # => {}
```
after this changes:
```ruby
bson_doc = BSON::Document.new(hello: 'world')
bson_doc.slice(:hello) # => {'hello' => 'world'}
```

add support for ActiveSupport Hash#slice method

---

lib/bson/regexp.rb
spec/bson/regexp_spec.rb

When a user attempts to call a method on BSON::Regexp::Ruby with arguments, an ArgumentError will be thrown. This change will actually pass down the arguments so that such errors will not get raised.

Fix ArgumentError in BSON::Regexp::Ruby

---

lib/bson.rb
lib/bson/object_id.rb
spec/bson/object_id_spec.rb
spec/bson_spec.rb

This will let `BSON::ObjectId#inspect` to return a string that can be evaluated into an equivalent object id. This would be super useful for copying and pasting object ids (especially when used with **Mongoid**).
A `BSON.ObjectId` constructor method passes the argument to `#from_string`, allowing object ids to behave kinda like literals.
Seemingly sending an arg to a constant as a constructor is similar to some behavior found in the standard lib: `Pathname('./lib')` or `Hash(a: 1, b: 2)`
If this is helpful, perhaps something similar can be implemented for `BSON::Binary` as well.
**Now**
``` ruby
>> BSON::ObjectId.new
=> BSON::ObjectId('559afa3e546f6e2631000000')
>> BSON::ObjectId('559afa3e546f6e2631000000')
=> BSON::ObjectId('559afa3e546f6e2631000000')
😃😃😃😃
>> Song.first.attributes
=> …
```

BSON::ObjectId#inspect returns a string that evals into an object id

---

ext/bson/native.c

The native extension implementation for `next_object_id` doesn't match Ruby's. The latter hashes the hostname while the former does not. This patch fixes the native extension to also MD5 hash the hostname.

md5 hash the hostname in the native extension

---

ext/bson/native.c
perf/bench.rb
spec/bson/timestamp_spec.rb

Added big endian support into the native code. Additionally corrected two issues common to all processor architecures:
1)  In the spec/bson/timestamp_spec.rb where the "#to_bson/#from_bson" test, the pack as was specified as ("l2") instead of (BSON::Int32::PACK * 2) 
2) In the benchmarking code, the FalseClass was being incorrectly bench marked against a BSON::Binary rather than a BSON::Boolean

Added big endian support into the native code

---

lib/bson/document.rb
spec/bson/document_spec.rb

Fixes https://jira.mongodb.org/browse/RUBY-1024.

RUBY-1024 #merge only yields for keys present in both hashes

---

lib/bson/regexp.rb

This PR unifies parsing of regular expressions across SSL and non-SSL connections thus fixing [RUBY-1048](https://jira.mongodb.org/browse/RUBY-1048). From the issue description:
> When accessing mongodb through SSL, Regexp attributes can't be read from the database. https://github.com/mongodb/bson-ruby/blob/master/lib/bson/regexp.rb#L156 hangs indefinitely as the options are NULL_BYTE terminated.
> Note that this issue only occurs when connecting through SSL. On an unencrypted connection, options are indeed "0" terminated and the bug thus doesn't manifest itself using non-encrypted connections.
> The parsing of the options itself is also subject to differences between SSL and non-SSL connections.
> Test case in Rails:
> ```ruby
class TestRecord
include Mongoid::Document
field :regex, …
```

Fix Regexp.from_bson for data from SSL connections

---

lib/bson/integer.rb
spec/bson/hash_spec.rb
spec/bson/integer_spec.rb

String and Symbol return a String, so Integer should as well.

RUBY-1071 Integer#to_bson_key should return a string to be consistent with other classes

---

lib/bson/hash.rb
lib/bson/integer.rb
lib/bson/symbol.rb
spec/bson/document_spec.rb
spec/bson/symbol_spec.rb

We previously serialized symbols as strings, since they were deprecated, but still set the type byte in the serialized BSON to `0x0E`, which was the deprecated symbol type. This pull changes the serialized type to be `0x02`, which is string, while still maintaining the ability to *deserialize* symbols when the type in the BSON being decoded is `0x0E`.

Serialize symbols to string types

---

ext/bson/native.c
lib/bson/object_id.rb

The [ObjectId spec](https://docs.mongodb.org/v3.0/reference/object-id/) says the counter should be initialized to a random value. Initialize the counter using Ruby's `Kernel#rand` in both the native extension and the pure Ruby implementation.

Initialize ObjectId counter to a random value

---

ext/bson/native-endian.h
ext/bson/native.c
spec/bson/object_id_spec.rb

Fix leverages the endian macros - was slated to do this anyways after the `ByteBuffer` rewrite.
Added a spec that generates 100k ids in succession and asserts there were no duplicates. Passes locally for me on OSX and also remotely on our Solaris 11.2 SPARC box.

RUBY-1091: Fix big endian object id generation.

---

lib/bson/regexp.rb

The BSON::Regexp::Raw#respond_to? method has a different signature than in [Rails](https://github.com/rails/rails/blob/a63760cea7d858984f83549019297221f18ed574/actionpack/lib/action_dispatch/testing/integration.rb#L385). This results in warnings like:
```
/home/reed/.gem/ruby/2.3.0/gems/mongoid-5.1.1/lib/mongoid/matchable/default.rb:35: warning: BSON::Regexp::Raw#respond_to?(:to_str) is old fashion which takes only one parameter                                                                                                                                       
/home/reed/.gem/ruby/2.3.0/gems/bson-4.0.2/lib/bson/regexp.rb:155: warning: respond_to? is defined here
```

Prevent warning from redefinition of :respond_to?

---

lib/bson/array.rb
lib/bson/binary.rb
lib/bson/code.rb
lib/bson/code_with_scope.rb
lib/bson/date.rb
lib/bson/date_time.rb
lib/bson/false_class.rb
lib/bson/float.rb
lib/bson/hash.rb
lib/bson/integer.rb
lib/bson/object_id.rb
lib/bson/regexp.rb
lib/bson/specialized.rb
lib/bson/string.rb
lib/bson/symbol.rb
lib/bson/time.rb
lib/bson/timestamp.rb
lib/bson/true_class.rb
spec/bson/array_spec.rb
spec/bson/hash_spec.rb

I noticed that we needed this set of changes when testing key validation with the driver.
The driver would try to serialize a write command like the following:
```ruby
{:insert=>"test", :documents=>[{"$testing"=>"value", :_id=>BSON::ObjectId('...')}], :ordered=>true, :writeConcern=>{:w=>1}}
```
The keys of the documents would not be validated because the top-level type is an Array. This pull request also applies key validation on hashes that are members of an Array so that we can actually use it from the driver.

RUBY-1092 Validate keys of hashes in an array

---

Rakefile
ext/bson/bson_native.c
ext/bson/extconf.rb
lib/bson.rb

Current extension name "native" is too loud in global namespace.
So I propose to add prefix "bson_" and change it to "bson_native".

Renamed extension from native to bson_native

---

lib/bson/config.rb

Removes this from the logs => warning: instance variable @validating_keys not initialized

Avoid ruby warnings

---

lib/bson/object_id.rb

Goes well with `#from_time` and `#to_s`

[for 4.2.0] Add BSON::ObjectId#to_time as alias to #generation_time

---

lib/bson/decimal128.rb
lib/bson/decimal128/builder.rb
spec/bson/decimal128_spec.rb
spec/bson/driver_bson_spec.rb

When looking into how Mongoid would handle converting BigDecimal objects previously "serialized" as Strings in the db to Decimal128 objects, I realized it would be simpler to handle Strings in the Decimal128 constructor. Otherwise, the method Decimal128#from_string would have to be used explicitly.

RUBY-1098 Support a String passed to Decimal128#new

---

lib/bson/timestamp.rb
spec/bson/timestamp_spec.rb

According to mongo specifications timestamp.to_json should be in the form of { "$timestamp": { "t": <t>, "i": <i> } }
source:
https://docs.mongodb.com/manual/reference/mongodb-extended-json/

Made timestamp as_json match mongo specifications

---

spec/bson/byte_buffer_spec.rb
src/main/org/bson/ByteBuf.java

Necessary for OP_MSG in the driver

Ensure that ByteBuf returns length when initialized with a String on JRuby

---

docs/tutorials/bson-v4.txt

Similar to https://github.com/mongodb/docs-ecosystem/pull/367
Fixes some typos and changes copy for clarity and correctness.

typos; copy fixes for ruby bson 4 tutorial

---

lib/bson/document.rb
spec/bson/document_spec.rb

Since rails 5.2 dropped ActiveSupport::Hash#slice in favor of delegating to
ruby 2.5+ Hash#slice, this broke the working functionality of BSON::Document#slice
when used with symbol arguments for keys.
[ close RUBY-1322 ]

Add support for #slice with symbol arguments

---

ext/bson/bson_native.c
spec/bson/byte_buffer_spec.rb
src/main/org/bson/ByteBuf.java

Hi,
The BSON::ByteBuffer#put_byte and BSON::ByteBuffer#put_bytes methods are crashing ruby when they receive parameters different to a String or a ByteBuffer object:
I added a couple of cases to reproduce this problem:
```
require 'bson'
BSON::ByteBuffer.new(1)
BSON::ByteBuffer.put_byte(1.2)
BSON::ByteBuffer.put_bytes([1])
```
If any of those 2 methods are invoked with an unexpected parameter, they are going to crash Ruby.
I tested it in ruby 2.4.3p205 and 2.5.1p57 in machines running MacOS and Linux (both x86_64) and I added  the output of one of those cases:
```
-- Crash Report log information --------------------------------------------
See Crash Report log file under the one of following:
* ~/Library/Logs/DiagnosticReports
* /Library/Logs/DiagnosticReports
for more details.
Don't …
```

Bug fix for the BSON::ByteBuffer#put_byte and BSON::ByteBuffer#put_bytes methods

---

lib/bson/document.rb
spec/bson/document_spec.rb

JIRA link: https://jira.mongodb.org/browse/RUBY-1677
After adding the `fetch` method (in #99) it changed it's signature. This PR makes sure it's the same as Ruby's `Hash#fetch`

RUBY-1677 Fix BSON::Document#fetch method signature

---

docs/tutorials/bson-v4.txt
lib/bson/decimal128.rb
perf/bench.rb
spec/bson/decimal128_spec.rb

To fix warning in Ruby 2.6:
> BigDecimal.new is deprecated; use BigDecimal() method instead
Similar to mongodb/mongoid#4616

RUBY-1653 Replace BigDecimal.new with BigDecimal() 

---

lib/bson/date.rb

JIRA: [RUBY-1702](https://jira.mongodb.org/browse/RUBY-1702)
I haven't found any nice solution for DateTimes - there is no way to get [`df`](https://github.com/ruby/date/blob/master/ext/date/date_core.c#L7113) attribute - which apparently holds second since beginning of day. I could use things like `offset`/`sec_fraction` etc., but this would be much harder to read + would actually create more instances (of Rational) than just using `to_time` as in current implementation.

RUBY-1702 Skip creating Time instance in Date serialization

---

bson.gemspec

Purpose:
- This change adds the link to the gem page on <https://rubygems.org>.
- This allows 3rd-party tools (e.g. Dependabot) to generate links to the repository, compare page, releases page, and so on.
See also:
- https://guides.rubygems.org/specification-reference/#metadata
- https://rubygems.org/gems/bson
Example:
- https://rubygems.org/gems/rspec-rails
- https://github.com/rspec/rspec-rails/blob/v3.8.2/rspec-rails.gemspec#L16-L22

RUBY-1958 Add GitHub repository URL to gemspec

---

ext/bson/bson_native.c
ext/bson/bson_native.h
ext/bson/libbson-utf8.c

https://jira.mongodb.com/browse/RUBY-1959

RUBY-1959 Specify exact reason in "invalid utf-8" exceptions

---

ext/bson/init.c
ext/bson/libbson-utf8.c
ext/bson/write.c
spec/bson/byte_buffer_write_spec.rb
spec/bson/document_spec.rb
spec/support/utils.rb
src/main/org/bson/ByteBuf.java

https://jira.mongodb.com/browse/RUBY-1978

RUBY-1978 Consistently handle data not in UTF-8 when writing strings/symbols

---

lib/bson/binary.rb
spec/bson/binary_spec.rb

https://jira.mongodb.com/browse/RUBY-2043

RUBY-2043 Ensure data is always BINARY-encoded in BSON::Binary objects and fix serialization of frozen strings

---

lib/bson/binary.rb
spec/bson/binary_spec.rb

Specification is [here](https://github.com/mongodb/specifications/blob/master/source/client-side-encryption/subtype6.rst).
This subtype is used to communicate with mongocryptd and store encrypted values in MongoDB.
(Not sure if there's anything more I need to do here.)

RUBY-2046 Add BSON Binary Subtype 6 to list of binary subtypes

---

.appveyor.yml
ext/bson/bson-native.h
ext/bson/endian.c

Original issue is: https://github.com/oneclick/rubyinstaller2/issues/167
See commit messages for description. The CI result looks like so: https://ci.appveyor.com/project/larskanis/bson-ruby
This github project has to be registered at https://ci.appveyor.com/projects/new , so that each `git push` triggers a CI build.

RUBY-2092 Fix build on Mingw and add Windows-CI

---

.evergreen/config.yml
ext/bson/init.c
spec/spec_helper.rb
spec/support/spec_config.rb

When `GC.compact` is called while using the Ruby driver, the bson gem sometimes segfaults. This is because there are global variables in the bson C extension that are not properly marked during GC, causing their memory to sometimes be compacted and the C extension to find another object in their place, hence the segfaults.
This is fixed by calling `rb_gc_register_mark_object` and passing in the VALUEs -- this tells the C extension to mark those global variables as roots during GC, which prevents their values from being moved.
Question: should there be a test for this?

RUBY-2185 Fix compaction-related segfault

---

ext/bson/bson-native.h
ext/bson/init.c
ext/bson/read.c
ext/bson/write.c
lib/bson/timestamp.rb
spec/bson/byte_buffer_read_spec.rb
spec/bson/byte_buffer_spec.rb
spec/bson/byte_buffer_write_spec.rb
spec/spec_tests/data/corpus/timestamp.json
src/main/org/bson/ByteBuf.java

I did this by adding a new function to the C code called put_uint32 which allows for unsigned 32 bit integers. (You need two 32 bit integers, seconds and increment, which gives the above mentioned 64 bits)
I have not implemented the Java version yet.

RUBY-2063 Changed Timestamps to allow for unsigned 64 bit integers

---

.travis.yml
ext/bson/read.c

This PR is to report the bug on s390x, bson >= 4.9.0, pointed by the JIRA ticket: [RUBY-2307](https://jira.mongodb.org/browse/RUBY-2307).
Adding some s390x cases for debugging.
Travis CI: https://travis-ci.org/github/mongodb/bson-ruby/builds/706149254
Thank you.
<hr />
Notes from @egiurleo:
I believe the issue is that the `pvt_get_string` method was using the wrong variable on big endian architectures when getting the int32 that represented the string length. It already declared a multi-purpose string length variable, so I just swapped out the little endian-specific variable for the one that works in both cases.

RUBY-2307 Segmentation fault on s390x

---

spec/bson/byte_buffer_spec.rb
spec/bson/hash_spec.rb
src/main/org/bson/ByteBuf.java

I did this by switching the mode on flipping the buffer.

Fix RUBY-2128 JRuby ByteBuffer advances read & write positions together

---

lib/bson/ext_json.rb
spec/spec_tests/data/corpus/binary.json

I added parsing logic in `ext_json.rb` to support parsing `$uuid` keys, and I synced our corpus spec tests to include the new uuid tests.

RUBY-2397 Support parsing $uuid as extended JSON representation for subtype 4 binary

---

.evergreen/config.yml
Gemfile
lib/bson/document.rb
spec/bson/document_spec.rb
spec/support/spec_config.rb

As described in https://jira.mongodb.org/projects/RUBY/issues/RUBY-2487
BSON::Document inherits `except` from Hash either when
- activesupport has added its extensions to Hash
- the ruby version is >= 3.0.0
The implementation in activesupport < 6.0 is such that keys were being
converted from symbols but this is not true of the implementation in
activesupport >= 6 or in ruby >= 3.0
Unlike `slice` this doesn't check whether the method is already defined - when I did that specs failed when run with WITH_ACTIVE_SUPPORT=1. I believe this is because active support is required after bson, so when bson/document.rb is being loaded `except` doesn't exist (yet) and active support later drops it's (bad) implementation on top.
I believe this same order loading thing affects slice - it is less obvious …

RUBY-2487 Add a local implementation of BSON::Document#except to work around ActiveSupport version not working correctly for symbol keys

---

.evergreen/config.yml
lib/bson/document.rb
spec/bson/document_spec.rb

Backport the .slice method from ActiveSupport core ext  hash but maintain the logic to normalize the symbol keys into strings.
Updated inline documentation to match return values, these return values now match the return types from ActiveSupport core ext Hash
[ close RUBY-2491, RUBY-2504 ]

RUBY-2491 RUBY-2504 Add slice method for all ruby versions, make it always return BSON::Document instances

---

lib/bson/error.rb
lib/bson/ext_json.rb
lib/bson/regexp.rb
spec/spec_tests/data/corpus/document.json
spec/spec_tests/data/corpus/regex.json
spec/spec_tests/data/corpus/top.json

After adding the tests I noticed that some of them failed, so I went ahead and attempted to implement my own solution.
Before this patch, the following case:
```
{
"description" : "Null byte in document key",
"string" : "\{\"a\\u0000\": 1 }"
}
```
Was being parsed as:
```
{ "a\u0000" => 1 } 
```
which is not working as intended. 
We expect it to raise an exception if there's a null byte in the key and this patch fixes that.

RUBY-2734 Prohibit embedded null bytes in strings used as BSON::Document hash keys, regexps and regexp options

---

lib/bson/ext_json.rb
lib/bson/regexp.rb
spec/bson/ext_json_parse_spec.rb
spec/bson/regexp_spec.rb

Evergreen patch for Ruby Driver with this branch of BSON ruby: https://spruce.mongodb.com/version/61ba2a57a4cf473d0db59180/tasks
The JRuby one still fails but I think it's not getting the right BSON ruby. I think that failure will be gone once this is merged into master

RUBY-2852 fix error where driver fails on integer key

---

docs/tutorials/bson-v4.txt

I added the note about the future functionality of BigDecimal into this PR.

RUBY-2861 add documentation for the loss of trailing zeroes

---

docs/tutorials/bson-v4.txt
ext/bson/read.c
lib/bson/big_decimal.rb
lib/bson/decimal128.rb
spec/bson/big_decimal_spec.rb
spec/bson/decimal128_spec.rb
spec/bson/hash_spec.rb
spec/runners/common_driver.rb

This PR is observing errors because of a bug where options are not passed to recursive calls to `#from_bson`. Investigating this further. 
EDIT: Now I'm observing errors in ruby 3.0

RUBY-2867 Change Decimal128 to deserialize to BigDecimal by default

---

lib/bson/regexp.rb
spec/bson/raw_spec.rb
spec/bson/regexp_spec.rb
spec/spec_tests/data/corpus/top.json

Since master is 5.0, I think we can remove support for integer options in Regexp::Raw constructor. This allows me to fix the bson corpus tests.

RUBY-2777 remove support for integer options for Regexp::Raw constructor

---

lib/bson/object_id.rb

Hello,
I am auditing some MongoDB Ruby code and found that `ObjectId` uses `Kernel.rand` to initialize the counter.
While `Kernel.rand` differs from implementation to implementation, it is likely seeded by at least the PID of the Ruby process.
In the `ObjectId` use case, since we already used `PID` in the tuple, we want to make sure other values in the tuple are independent from the `PID` as much as possible.
I know it might not have a concrete downside in practice, but just to be on the safe side, I would recommend initializing the counter with `SecureRandom` instead; what do you say?

RUBY-3137 Use SecureRandom to initialize ObjectId counter

---

lib/bson/big_decimal.rb
lib/bson/decimal128.rb
spec/bson/big_decimal_spec.rb
spec/bson/decimal128_spec.rb

Keep #to_big_decimal as an alias.

RUBY-3140 - Change Decimal128#to_big_decimal to #to_d following Ruby conventions

---

lib/bson/object_id.rb
src/main/org/bson/GeneratorExtension.java

Most of the warnings seen in the current version of bson-ruby are already fixed in master. There was just one warning left, which was caused by a method being redefined.
This was fixed by removing the extraneous plain-Ruby implementation of the `next_object_id` method on `ObjectId::Generator`. This pure-Ruby implementation was also (in JRuby) masking the faster, native implementation.

RUBY-3228 fix warnings visible via "-w"

---

spec/bson/dbref_legacy_spec.rb
spec/bson/decimal128_spec.rb
spec/runners/corpus.rb
spec/spec_tests/corpus_spec.rb
spec/spec_tests/data/corpus/decimal128-4.json
spec/spec_tests/data/corpus/decimal128-6.json
spec/spec_tests/data/corpus/decimal128-7.json

There were Decimal128 tests omitted because they were failing. The solution was to use type-specific parsing (e.g. `Decimal128::Builder`, versus `BSON::ExtJSON`) as required by the spec. No changes to code were necessary, only changes to the spec runner.

RUBY-1168 Correct BSON corpus Decimal128 test failures

---

lib/bson.rb
src/main/org/bson_ruby/ByteBuf.java
src/main/org/bson_ruby/GeneratorExtension.java
src/main/org/bson_ruby/MachineId.java
src/main/org/bson_ruby/NativeService.java

This is to avoid naming conflicts with the Java driver when loaded concurrently.
ref: https://jira.mongodb.org/browse/RUBY-1114

RUBY-1114 rename org.bson package to org.bson_ruby

---

.rubocop.yml
ext/bson/extconf.rb
ext/bson/init.c
lib/bson/array.rb
lib/bson/binary.rb
lib/bson/hash.rb
lib/bson/object_id.rb
lib/bson/regexp.rb

This enables Rubocop on files touched in RUBY-1410, RUBY-2056, RUBY-2264, and updates them as necessary so rubocop does not complain about them.

Enable Rubocop on a few files and update the files accordingly

---

ext/bson/init.c

As noted by @midnight-wonderer, the initialization code for the native C extension is using the wrong bit-mask for the random initial counter (noted here: https://github.com/mongodb/bson-ruby/discussions/315)
This PR corrects that mistake.

Use the correct bitmask to restrict result to 3 significant bytes

---

ext/bson/bson-native.h
ext/bson/extconf.rb
ext/bson/init.c
ext/bson/util.c

The recent update to bson-ruby--bringing the ObjectID generation in-line with the spec--used the `arc4random` method to generate random data with entropy. Sadly, `arc4random` is not available for many platforms, and the fallback was to use a naive implementation with `srand` and `rand`.
This PR changes the RNG in bson-ruby to use Ruby's own `SecureRandom` module. This is widely available, and uses proven entropy sources. It is conceivable that `SecureRandom` will not be available, in which case, the code again falls back to the naive `srand`/`rand` implementation, but this will be rare.

RUBY-3306 use Ruby's own SecureRandom to generate random bytes with entropy

---

release.sh
release/jruby/Dockerfile
release/jruby/install.sh
release/mri/Dockerfile

Final tweaks for BSON 5 release -- had to adjust JDK versions and minimum ruby versions and the JRuby version used to bundle the java gem. Also tweaked the release script to add a "dry run" mode.

final tweaks for BSON 5 release

---

ext/bson/read.c
ext/bson/write.c
lib/bson/version.rb

Using strlen may result in reading beyond the end of the buffer (if the buffer is not null-terminated). For this reason, we should avoid using strlen and prefer a more explicit approach that also takes into account the size of the buffer.
(Backport of #325)

SECBUG-240 Fix out-of-bounds reads (backport to 4.15-stable)

---

README.md

Copied additional information from the Ruby driver's README and adapted it to the `bson` gem's README

RUBY-3440: Add link to RUBY JIRA project to bson repo

---

.github/workflows/codeql.yml
README.md
lib/bson/version.rb

Preparing for the release of 5.0.1. Notable changes in this release include:
* [RUBY-3435](https://jira.mongodb.org/browse/RUBY-3435) Dates beyond 19 Jan 2038 were not representable in an ObjectID, but should have been.
* [RUBY-3508](https://jira.mongodb.org/browse/RUBY-3508) Certain malformed BSON packets could result in crashes when attempting to parse them.

RUBY-3481 Prepare for release of 5.0.1

---

.github/workflows/release.yml

The automated release process is currently skipping the part where it actually pushes the gems it produces to RubyGems. This PR fixes that, by correcting the value that the `dry_run` input is compared against. (When passed into another action, this input is apparently converted into a string, and requires quotes. When used directly, it remains a boolean, and must not be quoted.)

Fix release process so it pushes gems to RubyGems

---

lib/bson/binary.rb
spec/bson/binary_spec.rb

Because BSON::Binary instances represent binary data, it ought to be possible to compare their raw binary contents and decide which one would sort before or after another. This PR adds an implementation of `#<=>` to BSON::Binary. As long as both objects have the same binary type, this will compare the raw contents of the two objects, allowing homogeneous lists of BSON::Binary instances to be (e.g.) sorted.

RUBY-3533 Make BSON::Binary objects comparable

---

ext/bson/util.c

SecureRandom needs to be marked global so that it cannot be moved during GC compaction. When this happens the `pvt_SecureRandom` may reference a different object, or nothing at all causing a segfault.
I am not quite sure how a test would be written for this since it'd have to be run on its own, and it segfaults the process so the suite wouldn't run. This can be reproduced (on master), and shown resolved (on this branch) with the following:
```
rake compile
bundle console
irb> GC.verify_compaction_references(expand_heap: true, toward: :empty);
irb> BSON::ObjectId.new
```

RUBY-3557 Mark SecureRandom as Global

---

lib/bson/version.rb

Preparing for the release of 5.0.2. Notable changes in this release include:
- [RUBY-3533](https://jira.mongodb.org/browse/RUBY-3533) `BSON::Binary` objects are now instances of `Comparable`, and can be compared and sorted.
- [RUBY-3557](https://jira.mongodb.org/browse/RUBY-3557) Creating a new `BSON::ObjectId` could, due to GC compaction, result in segfaults. Many thanks to Zachery Hostens for identifying the root cause here, and proposing a fix!

Prep for 5.0.2

---

spec/spec_helper.rb

Since spec/spec_helper.rb uses StringIO class,
make this file explicitly require stringio.

TEST: explicitly require stringio

---

.github/workflows/bson-ruby.yml
.rubocop.yml
Gemfile
lib/bson/binary.rb
lib/bson/object_id.rb
lib/bson/regexp.rb
lib/bson/vector.rb
spec/runners/binary_vector.rb

Fixes RUBY-3665
This PR fixes and upgrade Rubocop, which is not currently passing in this repo.
Specific changes:
- Fix or skip cops so that Rubocop is green
- Upgrade Rubocop and related Rubocop gems
- Set min Ruby target version to 2.6 to match gemspec min Ruby version
- Remove conditional logic for Ruby < 2.6
- Add Rubocop step to Github Actions CI
- Add test coverage for Ruby 3.4 coverage to Github Actions while we're here
Please also ensure Rubocop is running in Nevergreen.

RUBY-3665 - Fix Rubocop

---

lib/bson/document.rb
spec/bson/document_as_spec.rb

Analogue of this [PR](https://github.com/mongodb/bson-ruby/pull/235)  but for `.deep_symbolize_keys!'
Inspired by few hours debugging why things behave weird
```
[DEVELOPMENT] tags/master-build-29117^0 irb(main):001:0> d = BSON::Document.new(foo: 'bar')
=> {"foo"=>"bar"}
[DEVELOPMENT] tags/master-build-29117^0 irb(main):002:0> d.deep_symbolize_keys!
=> {"foo"=>"bar"}
[DEVELOPMENT] tags/master-build-29117^0 irb(main):003:0> d.symbolize_keys!
(irb):3:in `<main>': symbolize_keys! is not supported on BSON::Document instances. Please convert the document to hash first (using #to_h), then call #symbolize_keys! on the Hash instance (ArgumentError)
```
It will be also great to backport it to 4 major, I can create PR if you'll accept this one.

Add error raise for deep_symbolize_keys!

---

.github/workflows/bson-ruby.yml

Updates the main CI file `bson-ruby.yml`
1. Add `workflow_dispatch` - this is used in other workflows here.  It allows maintainers to force a CI run.  It also does the same for users with forks of this repo.  Helpful for when changes to dependencies (or Ruby) happen that may affect this.
2. Update `actions/checkout` to `actions/checkout@v4`.  Used in other workflows
3. Add quotes to 3.0.  Actions' yaml parser truncates decimal zeros.  So, unquoted `3.0` will specify `3`, and unquoted `3.10` will specify `3.1`.  See [recent workflow](https://github.com/mongodb/bson-ruby/actions/runs/14909061493/job/41878540919#step:3:24).
3. WIndows - use `ucrt` instead of `mingw`.  Ruby 3.0 was the last publicly available `mingw` build.  Or, Ruby 3.5 will be released as a `ucrt` build.  Hence, better to …

Update bson-ruby.yml workflow

---

.github/workflows/codeql.yml
.github/workflows/release.yml
Rakefile
lib/bson/version.rb
product.yml

As part of RUBY-3643 (updating the release process), this adds some experimental changes to the release process for BSON-Ruby. Notably:
- Adds `spec/shared` to gain access to the new `candidate` rake tasks.
- Adds `product.yml` for compatibility with the new `candidate` rake tasks.
- Updates `.github/workflows/release.yml` to reference the new/updated (experimental) `pr-check`, `build`, and `publish` actions.
This includes no user-facing changes.

RUBY-3643 Update for new release process

---

Rakefile

Currently, projects that depend on bson-ruby's master branch (e.g. their Gemfile points to the bson-ruby repo) fail when the `rake compile` step tries to load the candidate tasks from spec/shared, because rubygems does not try to prepare any submodules.
This makes the Rakefile safe to run even when the spec/shared submodule has not been loaded.

Only try to load candidate tasks if the submodule has been loaded
